### ISSUE TITLE
recoveredAddress == whitelistSigningKey ????

### ISSUE THREAD

**Issue by rdyaktvt** [msfeldstein/EIP712-whitelisting#1]
Dear Michael,

I am trying to understand your solution. 

In line 68, we compare decoded signer address which is wallet owner with whitelistSigningKey which we set before minting process.
https://github.com/msfeldstein/EIP712-whitelisting/blob/83acf23a58914f56f63d9f09b14dc92e1de6b54d/contracts/EIP712Whitelisting.sol#L68

If I set whitelistSigningKey, same address of the wallet owner. Minting goes smooth.

But when I try another wallet address, of course fails.

When another wallet owner try to mint, ends with "Invalid Signature" error. Because other wallet owner address is different than whitelistSigningKey .

I create signature via following code. 

`const from = signer;
      const sign = await ethereum.request({
        method: 'eth_signTypedData_v4',
        params: [from, JSON.stringify(msgParams)],
      });
      console.log("sign: " + sign);
`

Why we test wallet owner address with whitelistSigningKey ?

I hope to hear you soon

Best Regards

**Comment by msfeldstein** [comment]
The signature needs to be created by the whitelistSigningKey, it can't be signed by the end user (otherwise anyone could just whitelist themselves right?).  You'll probably want to set up a backend service that signs peoples keys (using whatever type of verification you'd like, ie discord bot / twitter names / etc) and have your whitelist key be stored there to do signing.  Does that make sense?

**Comment by msfeldstein** [comment]
> decoded signer address which is wallet owner

This is incorrect.  The decoded address is the address that created the signature, not the wallet's owner.  It will not match msg.sender.

**Comment by rdyaktvt** [comment]
> The signature needs to be created by the whitelistSigningKey, it can't be signed by the end user (otherwise anyone could just whitelist themselves right?). You'll probably want to set up a backend service that signs peoples keys (using whatever type of verification you'd like, ie discord bot / twitter names / etc) and have your whitelist key be stored there to do signing. Does that make sense?

Dear Micheal,

Thaks for your kindly reply,

After many tests, I see that "whitelistkey" needs to be same as the metamask owner address for successfully signing. (only wallet address in the message changes hashes)

If I sign messages with whitelistkey for minters, any metamask owners who have this signed message could mint as whitelisted user. How we stop this in the code?

I am sure, I should be wrong, but I do not understand, where is trick?

Best Regards
