### ISSUE TITLE
Question about this approach

### ISSUE THREAD

**Issue by taiyangc** [msfeldstein/EIP712-whitelisting#4]
According to the most popular approaches:

1. Writing whitelisted accounts into contract storage. Super expensive to deploy but also dead simple
- Yes, easiest to implement and nothing can go wrong, except high gas fees.
2. Storing a merkle root to all the addresses that are whitelisted, and having the minter submit a merkle proof that their in that list. This is much cheaper, but a bit arduous to add people to, especially once things are deployed (though possible). [[Needs citation]]
- Even though this is harder to do after deployment, it still saves gas as minter only needs to submit one proof instead of a long list of addresses. And most projects won't need to update after it goes live!
3. This repos strategy: Signature verification using EIP-712. No gas, simple for end users to get a signature created using a basic web2 web service.
- Sure, this strategy is gas-free and can add users on the fly - but it has a few drawbacks: 1) It must be signed on a web2 service and cannot be "dynamically" added on a web3 service (which defeats the purpose of most web3 projects) 2) there is no tracking or record on-chain to prove the entire list of "whitelisted" users.

So in fairness, please put it clear that gas-free does not benefit web3 projects that much...

**Comment by msfeldstein** [comment]
I'm not sure what you're asking for here.  I think this was all made very clear on the readme.
